version: '3.8'

services:
  field-registration:
    build: .
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-field
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
